package prayit.simplebudget.core.components.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF6D5E0F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF8E287)
val onPrimaryContainerLight = Color(0xFF534600)
val secondaryLight = Color(0xFF206487)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC6E7FF)
val onSecondaryContainerLight = Color(0xFF004C6B)
val tertiaryLight = Color(0xFF7E570F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDDB1)
val onTertiaryContainerLight = Color(0xFF614000)
val errorLight = Color(0xFF904A43)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF73332D)
val backgroundLight = Color(0xFFFFF9EE)
val onBackgroundLight = Color(0xFF1E1B13)
val surfaceLight = Color(0xFFFFF8F3)
val onSurfaceLight = Color(0xFF201B13)
val surfaceVariantLight = Color(0xFFEAE2D0)
val onSurfaceVariantLight = Color(0xFF4B4739)
val outlineLight = Color(0xFF7C7767)
val outlineVariantLight = Color(0xFFCDC6B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF362F27)
val inverseOnSurfaceLight = Color(0xFFFBEFE2)
val inversePrimaryLight = Color(0xFFDBC66E)
val surfaceDimLight = Color(0xFFE3D8CC)
val surfaceBrightLight = Color(0xFFFFF8F3)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFEF2E5)
val surfaceContainerLight = Color(0xFFF8ECDF)
val surfaceContainerHighLight = Color(0xFFF2E6D9)
val surfaceContainerHighestLight = Color(0xFFECE1D4)

val primaryDark = Color(0xFFDBC66E)
val onPrimaryDark = Color(0xFF3A3000)
val primaryContainerDark = Color(0xFF534600)
val onPrimaryContainerDark = Color(0xFFF8E287)
val secondaryDark = Color(0xFF92CEF5)
val onSecondaryDark = Color(0xFF00344B)
val secondaryContainerDark = Color(0xFF004C6B)
val onSecondaryContainerDark = Color(0xFFC6E7FF)
val tertiaryDark = Color(0xFFF3BD6E)
val onTertiaryDark = Color(0xFF442B00)
val tertiaryContainerDark = Color(0xFF614000)
val onTertiaryContainerDark = Color(0xFFFFDDB1)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF561E19)
val errorContainerDark = Color(0xFF73332D)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF15130B)
val onBackgroundDark = Color(0xFFE8E2D4)
val surfaceDark = Color(0xFF17130B)
val onSurfaceDark = Color(0xFFECE1D4)
val surfaceVariantDark = Color(0xFF4B4739)
val onSurfaceVariantDark = Color(0xFFCDC6B4)
val outlineDark = Color(0xFF969080)
val outlineVariantDark = Color(0xFF4B4739)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFECE1D4)
val inverseOnSurfaceDark = Color(0xFF362F27)
val inversePrimaryDark = Color(0xFF6D5E0F)
val surfaceDimDark = Color(0xFF17130B)
val surfaceBrightDark = Color(0xFF3F382F)
val surfaceContainerLowestDark = Color(0xFF120D07)
val surfaceContainerLowDark = Color(0xFF201B13)
val surfaceContainerDark = Color(0xFF241F17)
val surfaceContainerHighDark = Color(0xFF2F2921)
val surfaceContainerHighestDark = Color(0xFF3A342B)

// Home tab accent colors
val homeParishesLight = Color(0xFF6D5E0F)
val homeParishesDark = Color(0xFFDBC66E)
val homeBibleLight = Color(0xFF1A5C8A)
val homeBibleDark = Color(0xFF7EC8F0)
val homeProfileLight = Color(0xFF3E6B4F)
val homeProfileDark = Color(0xFF8BC9A4)

// Parish tab accent colors
val parishCalendarLight = Color(0xFF8B3A5A)
val parishCalendarDark = Color(0xFFF092B5)
val parishAnnouncementsLight = Color(0xFF1A6B6A)
val parishAnnouncementsDark = Color(0xFF7ED4D3)
val parishDetailsLight = Color(0xFF7E570F)
val parishDetailsDark = Color(0xFFF3BD6E)
